feat: 멤버 프로필, 상세 정보, 프로젝트, 모임 정보 컴포넌트 분리
sopt-makers/sopt-playground-frontend pull request #1601
Opened 2024-10-23 07:31 UTC by pepperdad

### 🤫 쉿, 나한테만 말해줘요. 이슈넘버
- close #1596 

### 🧐 어떤 것을 변경했어요~?

멤버 프로필, 상세 정보, 프로젝트, 모임 정보를 컴포넌트로 분리했습니다!

CareerSection은 이미 컴포넌트로 분리되어 있어서, 스토리북에서 발생하는 오류만 수정했어요!

### 🤔 그렇다면, 어떻게 구현했어요~?

기존의 하나의 컴포넌트에 있던 뷰 로직을 분리했습니다.
상위에서 profile을 인자를 통해서 주면 각 Section에 해당하는 뷰에서 데이터를 보여줄 수 있도록 수정했습니다.

### ❤️‍🔥 당신이 생각하는 PR포인트, 내겐 매력포인트.

커피챗 페이지 상세조회 API 명세서에서 profile과 관련된 부분이 없어서, `useGetMemberProfileById`을 추가로 작성해서 프로필 정보를 가져와야할 것 같아요!

커피챗 상세 뷰에서 사용되는 부분은 아래 순서로 사용하시면 됩니다.

```typescript
<CareerSection
          careers={profile.careers}
          links={profile.links}
          skill={profile.skill}
          name={profile.name}
          email={profile.email}
          profileImage={profile.profileImage}
          memberId={memberId}
          isMine={profile.isMine}
        />

<DetailInfoSection profile={profile} />

<SoptActivitySection soptActivities={sortedSoptActivities} />

<ProjectSection profile={profile} memberId={memberId} meId={me?.id} />
```

MemberDetail.tsx에서 뷰들을 다 분리했어요! 
코드가 삭제된 부분이 많아서 보기 힘들 수도 있는데, 각 Section별 뷰들을 모두 컴포넌트로 분리했습니다!

### 📸 스크린샷, 없으면 이것 참,, 섭섭한데요?
<img width="719" alt="image" src="https://github.com/user-attachments/assets/dae54590-c85b-4def-80e3-0a5b2bc9d6d0">

2024-10-23 14:37 UTC, simeunseo requested changes
MemberDetaill이 아주 깔끔해졌네요!!!
고생 많았습니다 도영!!! 🚀🚀🚀

2024-10-23 14:37 UTC, simeunseo commented on src/components/members/detail/ActivitySection/MemberDetail.tsx
> +        />
![image](https://github.com/user-attachments/assets/5f297121-63cb-45f2-9be6-3213b2efe0b1)

현재 커리어, 스킬, 링크가 모두 없는 유저에 대해 CareerSection이 위와같이 뜨고 있어요!
기존에 있던 `(profile.careers?.length > 0 || profile.skill || profile.links?.length > 0)`이 조건문이 있어야할 것 같은데 혹시 없앤 이유가 있을까요?

2024-10-23 14:37 UTC, simeunseo commented on src/components/members/detail/MessageSection/index.tsx
> +  const isEmptyEmail = !email || email.length < 1;
falsy한 값일때 전부 empty로 처리해주어야하니 적절한 변경이네요 👍👍

2024-10-23 16:14 UTC, pepperdad commented on src/components/members/detail/ActivitySection/MemberDetail.tsx
> +        />
아 CareerSection 컴포넌트에도 아래와 같이 검사하는 로직이 있어요! 
```typescript
<Container>
      <>
        {careers?.length > 0 && (
        ... 
        {skill?.length > 0 && (
        ...
        {links?.length > 0 && (
```
근데 이 컨테이너 컴포넌트가 제일 상위에 있어서 저렇게 비어있는 경우에도 나오는 것 같아요! 
조건문 비교를 최상단으로 올려서 careers, skill, links 배열에 값이 있는 경우에 Container도 보이게 수정하겠습니다!

2024-10-23 16:29 UTC, simeunseo approved these changes
수정 내용 확인했습니다! 👍

2024-10-23 16:32 UTC, pepperdad commented
와우 빠른 확인 감사합니다!!
저도 은서 PR 얼른 리뷰할게용

2024-10-25 16:57 UTC, seojisoosoo reviewed
넘 깔끔해용 속 시원! 고생하셨습니다~

2024-10-27 14:26 UTC, merged