refactor: 헤더와 모바일 메뉴 리팩터링
sopt-makers/sopt-playground-frontend pull request #378
Opened 2023-01-26 19:19 UTC by Tekiter

### 🤫 쉿, 나한테만 말해줘요. 이슈넘버
- close #357 

### 🧐 어떤 것을 변경했어요~?
헤더와 모바일 메뉴 코드를 재작성했어요.

### 🤔 그렇다면, 어떻게 구현했어요~?

- 모바일 메뉴와 드롭다운 구현에 radix-ui를 사용했어요.
- 다른 팀 (Ex. 모임) 에서 쉽게 가져가 사용할 수 있도록, 아이콘 이미지 데이터를 별도의 파일에 따로 모았어요.

### ❤️‍🔥 당신이 생각하는 PR포인트, 내겐 매력포인트.

### 📸 스크린샷, 없으면 이것 참,, 섭섭한데요?

2023-01-27 08:11 UTC, NamJwong approved these changes
고생하셨습니다 😁

2023-01-27 08:24 UTC, NamJwong requested changes
오우 브랜치 받아서 돌려보는 걸 깜빡해서 뒤늦게 돌려봤는데

1. 피그마랑 디자인이 조금 달라요!
- 드롭다운 영역의 왼쪽/오른쪽 위 border-radius
- 프로필 버튼 패딩이 수상해요 폰트가 적용 안된 것 같기도 하고.. 패딩이 적은 것 같기도 하고

<img width="496" alt="image" src="https://user-images.githubusercontent.com/73823388/215039858-1bf93a8e-67a5-4cd6-b242-afa9c0d7ce0f.png">

<img width="357" alt="image" src="https://user-images.githubusercontent.com/73823388/215039894-bfc79f9a-149c-4d3f-b3aa-32b7c41638d2.png">

2. 모임 페이지가 404로 떠요!

2023-01-27 10:00 UTC, Tekiter commented on components/common/Header/desktop/DesktopHeader.tsx
> +  const pathMatch = (path: string) => router.pathname?.includes(path) ?? false;
> 다소 함수 이름같지 않게 느껴져요! 

`pathMatch`를 좀 더 직관적인 `isPathMatch`로 바꾸었어요!

> 렌더링 될 때마다 모든 MenuLink 컴포넌트들에 대해 함수가 실행되는 것이 조금 걸리네요

함수를 하나 더 만들어 실행하는 것은 성능적으로 영향이 거의 없어요. 중요한 것은 실제 무슨 연산을 하고, 얼마나 자주 실행되냐에요.
이 함수는 많아 봤자 약 200자 이내의 짧은 string에 대해서 includes 함수를 실행하는 함수에요. 이 연산은 아주 빠르게 수행할 수 있어서 성능에 영향을 거의 끼치지 않아요!

2023-01-27 10:06 UTC, Tekiter commented on components/common/Header/desktop/DesktopHeader.tsx
> +  const pathMatch = (path: string) => router.pathname?.includes(path) ?? false;
> currentPath라는 값을 useMemo로 만들어놓고 pathname이 변경될 때마다 갱신해서 이 값을 MenuLink 컴포넌트의 isActive에 활용하는 것은 어떤가요?

이렇게 해도 결국 각 컴포넌트에서 비교를 수행해야 하기 때문에 지금 방식보다 성능이 빨라지지 않아요! 오히려 `useMemo`의 오버헤드 때문에 성능이 더 안좋아질 수 있어요.
https://blog.logrocket.com/rethinking-hooks-memoization/

2023-01-27 10:09 UTC, Tekiter commented
> 드롭다운 영역의 왼쪽/오른쪽 위 border-radius

z-index 때문에 헤더가 위로 겹쳐서 드롭다운이 잘렸네요.. 해당 문제 드롭다운을 밑으로 내려서 해결했어요.

> 프로필 버튼 패딩이 수상해요 폰트가 적용 안된 것 같기도 하고.. 패딩이 적은 것 같기도 하고

폰트가 적용 안된게 맞았네요! 제 실수에요 ㅎㅎ.. 체크해줘서 감사해용

2023-01-27 15:52 UTC, NamJwong commented on components/common/Header/desktop/DesktopHeader.tsx
> +  const pathMatch = (path: string) => router.pathname?.includes(path) ?? false;
질문: 연산 마다 어느 정도 시간이 걸릴지 감이 없어서 이런 걸 판단하기가 힘들다.. 도대체 useMemo는 언제 써야 하지?

@Tekiter 의 답변
1. 배열이나 객체의 원소가 20개 이상을 초과할 것 같을 때
2. 딱 봐도 시간이 오래 걸릴 것 같은 연산
  - O(n) 초과
  - 외부 접근(DOM, API, new Object)

2023-01-28 09:32 UTC, NamJwong approved these changes
🚀👍

2023-01-28 09:37 UTC, merged